import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import './globals.css'

// const inter = Inter({ subsets: ['latin'],  })

export const metadata: Metadata = {
  title: 'Create Next JS App',
  description: 'Generated by web developer',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`relative`}>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
